apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: val-poi-map-app-dev
  annotations:
    argocd/app-name: val-poi-map-app-dev
    backstage.io/kubernetes-id: val-poi-map-app
    backstage.io/kubernetes-namespace: val
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-2024/val-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-qxs8d.dusy.p1.openshiftapps.com/dev-pipelines/ns/val/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-qxs8d.dusy.p1.openshiftapps.com/k8s/ns/val/deployments/val-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-qxs8d.dusy.p1.openshiftapps.com/#https://github.com/rhdh-2024/val-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://val-poi-map-app-val.apps.rosa-qxs8d.dusy.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:user1"
  system: workshop-system-val
  consumesApis:
    - gateway-api-val
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-val
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:user1"
